### ISSUE TITLE
some notes 

### ISSUE THREAD

**Issue by aithedev** [xtekky/TikTok-Web-Reverse#1]
1. i doubt either the python or the js version is yours since you dont even make the algos you have loll
2. if i wanted to be a skid as well as purposely leak "your" bogus script, i would leak the python version, not a js version since im not a js dev
3. i found the js bogus randomly in my files, never claimed to have made it either way

**Comment by aithedev** [comment]
its clear that you didnt write the bogus script, your code is inconsistent with the other files

++
(referring to you)
![image](https://user-images.githubusercontent.com/105955582/222860104-0649b01f-6ef7-496f-9a9b-427d5374c130.png)

Not trynna send any hate but you started it by calling me a skid even though you can see that i'm not and you are..

**Comment by PSVita-Dev** [comment]
I need to add that the mssdk stuff is from my repo, just translated to python. He says "credits for the help of @azubisminir" , but that doesnt say that I reversed the mssdk stuft. OFC, some stuff is made nicer but he still didnt reverse it

**Comment by PSVita-Dev** [comment]
The JS or Python bogus is not from me , but I think its from a chinese
